### ISSUE TITLE
Set screen recording rectangle as a feature

### ISSUE THREAD

**Issue by karolswdev** [louis030195/screen-pipe#113]
So in my case, I think it would be useful to be able to constraint the recording to a specified rectangle on my screen. I am currently running a 5120x1444 monitor, which means it's insanely wide. This typically means that I tile my windows so that my main workspace is middle and anything else goes on the sides. I may not always be interested in what's happening on the sides - therefore, it would be a great thing to be able to specify that in the CLI so that I can only record what's important (and doesn't overload Tesseract too much, too!)

**Comment by louis030195** [comment]
#90 related

got it

will prioritze monitor stuff

**Comment by louis030195** [comment]
@karolswdev  3b186fb

added monitor selection:

```bash
screenpipe --list-monitors
screenpipe --monitor-id 1
```

PS: also improved app_name saved during capture (i use the biggest window currently shown, but we still capture the whole monitor text atm)

**Comment by karolswdev** [comment]
@louis030195 I'd argue it's not complete, at least not in the sense that I was asking for. I like the feature, don't get me wrong, and most people will use just the monitor selection, but like I said, when running ultrawide monitors it would be great to also be able to constrain the recording to a specific rectangle, so as not to overload OCR. My tesseract is using insane amounts of CPU with my 5120x1440 setup.

**Comment by louis030195** [comment]
@karolswdev got it, had it planned but more for next week, will do!
