### ISSUE TITLE
[ingest] Ensure Tesseract OCR version >= V5

### ISSUE THREAD

**Issue by PSU3D0** [louis030195/screen-pipe#23]
Version 5 of Tesseract has improved OCR accuracy. Screen-pipe should attempt to install the latest version, which involves building from source.

**Comment by m13v** [comment]
Frankie, thanks for the suggestion!

**Comment by louis030195** [comment]
@PSU3D0 are you on linux? otherwise we launch 

`screenpipe --ocr-engine windows-native` 

or 

`screenpipe --ocr-engine apple-native`
