### ISSUE TITLE
memory leak on windows

### ISSUE THREAD

**Issue by wangshifeng** [louis030195/screen-pipe#40]
![image](https://github.com/user-attachments/assets/3c50668a-ba63-4809-bf6b-6608e026606d)

I addressed a small problem, and I got it running on the Windows, but I discovered a noticeable memory leak.

**Comment by louis030195** [comment]
curious what was the small problem?

indeed related to https://github.com/louis030195/screen-pipe/issues/39

did the process crash then?

what was the exact cli?

**Comment by wangshifeng** [comment]
thanks for your reply! 
it’s just an issue with a filename causing an error on Windows, and I’ve submitted a PR. #46 

about memory leak, 

```
cargo build --release
cd target/release
screenpipe.exe --disable-audio
```
after running, from the output logs,  memory usage continuous increasing. i think it would OOM crash.

do you have any suggestions ?  have you encountered this on Mac？

**Comment by louis030195** [comment]
https://github.com/louis030195/screen-pipe/issues/39

did it crash? 
you can disable audio

do you have Nvidia GPU or AMD or something else?
it works much better with an AI accelerator
on mac it uses mac NPU (M3 max for me)


anyway i'm going to work on performance in upcoming days

**Comment by louis030195** [comment]
@wangshifeng by any chance did you try latest version of screenpipe?

**Comment by louis030195** [comment]
@wangshifeng let me know if the issue happens again!
