### ISSUE TITLE
tweak api ux

### ISSUE THREAD

**Issue by louis030195** [louis030195/screen-pipe#43]
```rs

        let app = Router::new()
            .route("/search", get(search))
            .route("/recent", get(get_by_date_range))
            .layer(CorsLayer::permissive())
            .with_state(app_state);
```

i think we should remove /recent and make /search have time filters + other stuff

just a powerful search, clean, would be a dream

cc @m13v

**Comment by m13v** [comment]
yeah, let's focus on making metadata easily searchable

**Comment by louis030195** [comment]
@m13v also was thinking we should have a way to annotate data through api

use case:

have some processing script that annotate rows with a llm for example

"between 8 am and 10 am i was doing work on X project"

"between 9 am and 9.30 am i context switched 30 times"

or idk, bunch of stuff to do

**Comment by m13v** [comment]
we need to extract entities, and we don't know them until the user confirms
them. E.g. based on the recent screens it looks like you are working on
that or that, what would you call this project, is this a project, etc.

**Comment by louis030195** [comment]
hm no

AI can extract things without human intervention, that's how LLM works (self supervised learning)
