### ISSUE TITLE
[getting started] brew install screenpipe

### ISSUE THREAD

**Issue by louis030195** [louis030195/screen-pipe#6]
atm had isssues w cli building cross platofmr 

https://github.com/louis030195/screen-pipe/actions/runs/9660680149

**Comment by louis030195** [comment]
https://github.com/louis030195/screen-pipe/blob/main/install.sh

**Comment by louis030195** [comment]
https://github.com/louis030195/screen-pipe/issues/2

not sure yet whats best

not super familiar with wasm yet

**Comment by louis030195** [comment]
stuck with this

>ld: library 'stdc++' not found

tried thousands way to fix this c++ shit without success atm, anyone?

basically just want to build a dmg/pkg/whatever on macos that is signed and did the notoriety thing for macos to avoid getting the "unsecure app" thing

and on linux just run it ..

**Comment by louis030195** [comment]
if by any chance someone has a apple dev account - mine is completely fucked up and support does not answer :(

need it to sign cli

**Comment by lucacri** [comment]
> if by any chance someone has a apple dev account - mine is completely fucked up and support does not answer :(
> 
> need it to sign cli

DM me if you still need it

**Comment by louis030195** [comment]
@lucacri that would be awesome!

if you have 15-30 min i bet we can solve it in this timeframe, i just need a "dev id application" and do things with base64 encryption + password, updating github action secret, running the github action locally to test if the signing work on mac and that would be done (15-30 min)

https://cal.com/louis030195/d

would be super nice, then people would just need to do "curl" and have screenpipe installed in less than 10s on mac

https://github.com/louis030195/screen-pipe/blob/97f2192c421352548e4e5afc095a0323f64525bc/.github/workflows/release.yml

**Comment by louis030195** [comment]
anyone want to contribute to this the preferred path is to implement homebrew for mac atm (so brew pick right ffmpeg and stuff. linux owkrs atm, windows idk, who use windows anyway? 🤓

**Comment by louis030195** [comment]
done - ened to automat4e it now
