### ISSUE TITLE
Dioxus example Build Failed

### ISSUE THREAD

**Issue by DmacMcgreg** [louis030195/screen-pipe#69]
## Steps to Reproduce:

1. Download repo to ~/sp folder
2. `cd ~/sp/examples/apps/screenpipe-app-dioxus`
3. install tailwind
4. install rust, cargo, dx cli
5. dx serve --hot-reload --platform desktop

dx serve --hot-reload --platform desktop
- ⚙ Compiling path+file:///Users/davidmcgregor/sp/screenpipe-server#0.1.0                                                                                                             error[E0061]: this function takes 4 arguments but 3 arguments were supplied
   --> src/main.rs:146:5
    |
146 |     ResourceMonitor::new(memory_threshold, runtime_threshold, false)
    |     ^^^^^^^^^^^^^^^^^^^^--------------------------------------------
    |                         ||                 |
    |                         ||                 unexpected argument of type `u64`
    |                         |unexpected argument of type `f64`
    |                         three arguments of type `Duration`, `u32`, and `tokio::sync::mpsc::Sender<RestartSignal>` are missing
    |
note: associated function defined here
   --> /Users/davidmcgregor/sp/screenpipe-server/src/resource_monitor.rs:23:12
    |
23  |     pub fn new(
    |            ^^^
help: did you mean
    |
146 |     ResourceMonitor::new(false, /* Duration */, /* u32 */, /* tokio::sync::mpsc::Sender<RestartSignal> */)
    |                         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

error[E0061]: this function takes 7 arguments but 8 arguments were supplied
   --> src/main.rs:159:25
    |
159 |         if let Err(e) = screenpipe_server::start_continuous_recording(
    |                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
...
164 |             control_rx,
    |             ---------- unexpected argument of type `tokio::sync::mpsc::Receiver<_>`
    |
note: expected `Arc<SegQueue<(AudioDevice, DeviceControl)>>`, found `Receiver<(AudioDevice, DeviceControl)>`
   --> src/main.rs:166:13
    |
166 |             audio_devices_control_receiver,
    |             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    = note: expected struct `Arc<crossbeam_queue::seg_queue::SegQueue<(AudioDevice, DeviceControl)>>`
               found struct `tokio::sync::mpsc::Receiver<(AudioDevice, DeviceControl)>`
note: function defined here
   --> /Users/davidmcgregor/sp/screenpipe-server/src/core.rs:43:14
    |
43  | pub async fn start_continuous_recording(
    |              ^^^^^^^^^^^^^^^^^^^^^^^^^^
help: remove the extra argument
    |
163 ~             audio_chunk_duration,
164 |             vision_control,
165 ~             /* Arc<crossbeam_queue::seg_queue::SegQueue<(AudioDevice, DeviceControl)>> */,
    |

error[E0308]: mismatched types
   --> src/main.rs:192:13
    |
188 |         let server = Server::new(
    |                      ----------- arguments to this function are incorrect
...
192 |             audio_sender_for_server.as_ref().clone(), // Clone the inner Sender
    |             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ expected `Arc<SegQueue<(AudioDevice, DeviceControl)>>`, found `Sender<(AudioDevice, DeviceControl)>`
    |
    = note: expected struct `Arc<crossbeam_queue::seg_queue::SegQueue<(AudioDevice, DeviceControl)>>`
               found struct `tokio::sync::mpsc::Sender<(AudioDevice, DeviceControl)>`
note: associated function defined here
   --> /Users/davidmcgregor/sp/screenpipe-server/src/server.rs:458:12
    |
458 |     pub fn new(
    |            ^^^

Some errors have detailed explanations: E0061, E0308.
For more information about an error, try `rustc --explain E0061`.
error: could not compile `screenpipe-app-dioxus` (bin "screenpipe-app-dioxus") due to 3 previous errors
  ❌ Build failed.                                                                                                                                                                    Error: 🚫 Serving project failed:

Caused by:
    Build failed

**Comment by louis030195** [comment]
thanks for reporting! @DmacMcgreg 

the dioxus app is still a WIP, i could remove it from the files or would love a contribution to make it work

i'd recommend starting from the CLI if you want

try to build the CLI and run it

**Comment by louis030195** [comment]
if you want to contribute to the dioxus app I'd recommend just starting new dioxus app and running the built CLI from withing the dioxus setup code using `tokio` `Command` something like this:

```rs
use tokio::process::Command;

let output = Command::new("screenpipe")
        .output().await.unwrap();
```

**Comment by DmacMcgreg** [comment]
Oh i see! Thanks for the response. I was actually trying to get "the" Desktop app running.
I'm guessing this is not the one then?
Is there any instructions on building and running that one?

**Comment by louis030195** [comment]
@DmacMcgreg hey you can try to build it from there https://github.com/louis030195/screen-pipe/blob/main/.github/workflows/release-app.yml

otherwise DM me can send you a free trial
