### ISSUE TITLE
Latest release 0.1.43 breaks brew formula

### ISSUE THREAD

**Issue by moltar** [louis030195/screen-pipe#78]
Brew formula has `v` prefix for the tag: https://github.com/louis030195/screen-pipe/blob/dce90b42f7361b716ed2ede2518095308663a0d3/Formula/screenpipe.rb#L4

Meanwhile, the release skipped the `v`.

![screenshot-20240731T110550-yRZOesIV@2x](https://github.com/user-attachments/assets/19afbd58-44f5-43a6-8061-092ddf1f51bf)

**Comment by louis030195** [comment]
@moltar oh thanks, been automating the process, will fix the CI, does it work now?

**Comment by moltar** [comment]
No, assets still have the old path.

![screenshot-20240731T111124-VQDqAB9b@2x](https://github.com/user-attachments/assets/c8f338cc-cf39-4cf6-af45-d8a08b4947ee)

You can check it this way:

```sh
curl -f https://github.com/louis030195/screen-pipe/releases/download/v0.1.43/screenpipe-0.1.43-aarch64-apple-darwin.tar.gz
```

If you get this, then the formula is still broken:

```
curl: (22) The requested URL returned error: 404
```
