### ISSUE TITLE
Error: A backend-specific error has occurred: The user declined TCCs for application, window, display capture

### ISSUE THREAD

**Issue by moltar** [louis030195/screen-pipe#79]
I am getting this error on the first run of the CLI tool on a macOS.

> Error: A backend-specific error has occurred: The user declined TCCs for application, window, display capture

**Comment by moltar** [comment]
Probably related to macOS privacy preferences. But not clear how to grant a CLI access. Tried drag & dropping the binary into the list and it works. But nothing has changed from the error message. Maybe I need to add it to more categories, but not sure which ones, as the error isn't specific enough for each permission.

Also, there might be a corner case with brew, because brew links into `/opt/homebrew/bin/screenpipe`, meanwhile the _actual_ binary lives elsewhere. Dragging & dropping `/opt/homebrew/bin/screenpipe` into the permission list seems to indicate that it adds a link, rather than the original. Not sure if that matters tho.

**Comment by louis030195** [comment]
When you start the cli it should pop a permission dialog for recording 

Otherwise search "recording" in settings and enable screenpipe 

Sec will send some screenshots

**Comment by louis030195** [comment]
https://github.com/louis030195/screen-pipe/blob/main/content/docs/NOTES.md

**Comment by moltar** [comment]
> When you start the cli it should pop a permission dialog for recording

It doesn't. Not sure if it's my system or what, but it exits immediately with the error, and no typical macOS permission screens are displayed.

**Comment by moltar** [comment]
Added it to the list. The _actual_ binary too, not the linked one. Yet still get the same error.

![screenshot-20240731T141722-veQDXlKe@2x](https://github.com/user-attachments/assets/13944166-2f99-4fbe-a5b9-c846fafd454a)

**Comment by moltar** [comment]
> try to remove the permission 

Tried that.

> multiple monitors sometimes it's hiding somewhere

Not the case. I did check.

> is it mac M or intel?

It's M1

**Comment by louis030195** [comment]
what terminal do you use?

![Screenshot 2024-07-31 at 20 50 27](https://github.com/user-attachments/assets/46163fb3-5d02-4776-8347-0d68fc97ce79)

i have this

but the screenpipe one is the desktop app

i think the CLI is my terminal Alacritty

**Comment by louis030195** [comment]
https://github.com/user-attachments/assets/1d187b4d-364c-4e9d-a173-4a7e782dc914

**Comment by moltar** [comment]
Good call on the terminal! Indeed, when I grant iTerm2 access, everything works.

But that raises a question 🤔 I don't really want iTerm2 to have _full_ access, as that means _any_ CLI tool, or npm script, and everything else gets the same level of permissions.

**Comment by louis030195** [comment]
@moltar yeah had same thought, you can [get the desktop app](https://screenpi.pe/) alternatively 🙂
