### ISSUE TITLE
Strange audio transcriptions when silent

### ISSUE THREAD

**Issue by moltar** [louis030195/screen-pipe#86]
It seems during the moments of silence, the transcription goes insane and writes this kind of stuff:

> [2024-08-01T10:34:41Z INFO  screenpipe_audio::stt]   0.0s-...:  I'm going to use the other side of the screen. I'm going to use the other side of the screen. I'm going to use the other side of the screen. I'm going to use the other side of the screen. I'm going to use the other side of the screen. I'm going to use the other side of the screen. I'm going to use the other side of the screen. I'm going to use the other side of the screen. I'm going to use the other side of the screen. I'm going to use the other side of the screen. I'm going to use the other side of the screen. I'm going to use the other side of the screen. I'm going to use the other side of the screen. I'm going to use the other side of the screen. I'm going to use the other side of the screen. I'm going to use the other side of the screen. I'm going to use the other side of the screen. I'm going to use the other side of the screen. I'm going to use the other

> [2024-08-01T10:37:11Z INFO  screenpipe_audio::stt]   0.0s-...:  I'm going to do this. I'm going to do this. I'm going to do this. I'm going to do this. I'm going to do this. I'm going to do this. I'm going to do this. I'm going to do this. I'm going to do this. I'm going to do this. I'm going to do this. I'm going to do this. I'm going to do this. I'm going to do this. I'm going to do this. I'm going to do this. I'm going to do this. I'm going to do this. I'm going to do this. I'm going to do this. I'm going to do this. I'm going to do this. I'm going to do this. I'm going to do this. I'm going to do this. I'm going to do this. I'm going to do this. I'm going to do this. I'm going to do this. I'm going to do this. I'm going to do this. I'm going to do this

> [2024-08-01T10:37:41Z INFO  screenpipe_audio::stt]   0.0s-...:  I'm going to make a video about the next video. I'm going to make a video about the next video. I'm going to make a video about the next video. I'm going to make a video about the next video. I'm going to make a video about the next video. I'm going to make a video about the next video. I'm going to make a video about the next video. I'm going to make a video about the next video. I'm going to make a video about the next video. I'm going to make a video about the next video. I'm going to make a video about the next video. I'm going to make a video about the next video. I'm going to make a video about the next video. I'm going to make a video about the next video. I'm going to make a video about the next video. I'm going to make a video about the next video. I'm going to make a video about the next video. I'm going to make a video about the next video. I'm going to make a video

> [2024-08-01T10:39:12Z INFO  screenpipe_server::core] Inserting audio chunk: Some("<|0.00|> I'm going to do a little bit of a little bit of a little bit of a little bit of a little bit of a little bit of a little bit of a little bit of a little bit of a little bit of a little bit of a little bit of a little bit of a little bit of a little bit of a little bit of a little bit of a little bit of a little bit of a little bit of a little bit of a little bit of a little bit of a little bit of a little bit of a little bit of a little bit of a little bit of a little bit of a little bit of a little bit of a little bit of a little bit of a little bit of a little bit of a little bit of a little bit of a little bit of a little bit of a little bit of a little bit of a little bit of a little bit of a little bit of a little bit of a little bit of a little bit of a little bit of a little bit of a little bit of a little bit of a little bit of a little bit of a little bit of a little")

**Comment by moltar** [comment]
Btw, I have a fan nearby, but it's not too loud. Could be picking up the white/brown noise from that.

**Comment by louis030195** [comment]
yes sorry about that we added a noise filter in new version

you can upgrade to latest version using `brew upgrade` and `brew upgrade screenpipe` 

note that then when running the CLI it is now using by default Deepgram which is a cloud model much more powerful than the local one

you can keep local model using `screenpipe --cloud-audio-off`

**Comment by moltar** [comment]
> CLI it is now using by default Deepgram

Does that need an API key?

**Comment by louis030195** [comment]
> > CLI it is now using by default Deepgram
> 
> Does that need an API key?

@moltar nope, we have bunch of credits after winning hackathon(s) so we offer it for free!

**Comment by moltar** [comment]
Do they use that data in some nefarious ways? ;)
