### ISSUE TITLE
How to capture external screens?

### ISSUE THREAD

**Issue by moltar** [louis030195/screen-pipe#87]
I have the main MacBook screen and an external screen via USB-C.

Is it possible to capture both screens?

If not, is it possible to alter the captured screen to the external one?

Thanks.

**Comment by moltar** [comment]
> i dont think many people will want to capture multiple screens

Really? pretty much everyone i know uses multiple screens. 🤷🏼 

> personally never use multi monitor, gives me back pain ^^

I use multi-ish monitor.

My setup is like this:

![screenshot-20240801T171325-oA29SfzO@2x](https://github.com/user-attachments/assets/dddc3335-ec7b-4beb-9a7a-57a5a9f2ea35)

Where the bottom screen is the MacBook, which I also use as a keyboard. And I only use it for running generic apps that I do not often need to check, like term, calendar. But all of the work happens on the single external display.

**Comment by PixelDJ** [comment]
> hey yeah atm it's using the default screen so mac screen:
> 
> https://github.com/louis030195/screen-pipe/blob/8e1728f7db08072698bc2ee815b1148e167d1a76/screenpipe-vision/src/core.rs#L99
> 
> will implement multi monitor + selection soon, it's prob easy task, just concern now is CPU usage for OCR but i dont think many people will want to capture multiple screens
> 
> also we're going to use better OCR soon, maybe using GPU (apple native, or cloud, or something else like small multimodal LLM)

Thanks for looking into this!

It would be nice to see monitor selection at least. On one of my Windows PCs, the primary monitor is not captured because the "first" screen is actually the top monitor while the primary is the second (bottom) screen.

**Comment by louis030195** [comment]
@PixelDJ @moltar 3b186fb

added monitor selection:

```bash
screenpipe --list-monitors
screenpipe --monitor-id 1
```
